
import React, { useState } from 'react';

const Legal: React.FC<{ initialTab?: 'tos' | 'privacy' | 'disclaimer' }> = ({ initialTab = 'tos' }) => {
  const [tab, setTab] = useState(initialTab);

  const renderContent = () => {
    switch (tab) {
      case 'tos':
        return (
          <div className="space-y-6 animate-in fade-in duration-500">
            <h3 className="text-2xl font-bold text-slate-900 legal-serif">Terms of Service</h3>
            <p className="text-xs text-slate-400 font-bold uppercase tracking-widest">Last Updated: May 2024</p>
            <div className="prose prose-slate prose-sm max-w-none font-medium leading-relaxed">
               <p>Welcome to Vidhi AI. By accessing this Enterprise Legal Operating System, you agree to these terms.</p>
               <h4 className="text-slate-900 font-bold">1. Professional Responsibility</h4>
               <p>Vidhi AI is a productivity tool for legal professionals. It does not practice law. The user (Advocate) retains sole responsibility for all court filings, legal advice, and professional conduct. AI-generated drafts must be verified by licensed counsel.</p>
               <h4 className="text-slate-900 font-bold">2. Use License</h4>
               <p>Subject to your subscription tier, we grant a non-exclusive license to use the RAG research and drafting engines for professional legal purposes.</p>
               <h4 className="text-slate-900 font-bold">3. Data Stewardship</h4>
               <p>We implement firm-level isolation. You own your data. We own the underlying AI infrastructure and proprietary legal knowledge graph.</p>
            </div>
          </div>
        );
      case 'privacy':
        return (
          <div className="space-y-6 animate-in fade-in duration-500">
            <h3 className="text-2xl font-bold text-slate-900 legal-serif">Data Processing Policy</h3>
            <p className="text-xs text-slate-400 font-bold uppercase tracking-widest">DPDP COMPLIANT V1.0</p>
            <div className="prose prose-slate prose-sm max-w-none font-medium leading-relaxed">
               <p>Your privacy is our primary engineering constraint.</p>
               <h4 className="text-slate-900 font-bold">Data Minimization</h4>
               <p>We only collect data necessary to provide high-fidelity RAG results. This includes your name, email, and firm identity.</p>
               <h4 className="text-slate-900 font-bold">Document Privacy</h4>
               <p>Pleadings and judgments uploaded for analysis are processed in a volatile state and stored in an encrypted shard isolated to your firm ID.</p>
               <h4 className="text-slate-900 font-bold">Consent</h4>
               <p>By using the "Intelligence" features, you consent to the processing of document text by Gemini Pro APIs under enterprise privacy agreements.</p>
            </div>
          </div>
        );
      case 'disclaimer':
        return (
          <div className="space-y-6 animate-in fade-in duration-500">
            <h3 className="text-2xl font-bold text-slate-900 legal-serif">Legal Intelligence Disclaimer</h3>
            <p className="text-xs text-slate-400 font-bold uppercase tracking-widest">IMPORTANT NOTICE</p>
            <div className="prose prose-slate prose-sm max-w-none font-medium leading-relaxed">
               <div className="p-8 bg-amber-50 border border-amber-100 rounded-3xl text-amber-900 font-bold italic">
                 "VIDHI AI IS NOT A LAWYER AND DOES NOT PROVIDE LEGAL ADVICE."
               </div>
               <p>The information, research, and drafts generated by Vidhi AI are for educational and professional assistance purposes only.</p>
               <h4 className="text-slate-900 font-bold">Accuracy of AI</h4>
               <p>While we use Gemini 3 Pro with high thinking budgets, LLMs can hallucinate case law or statutory provisions. Always verify citations against official Gazette or AIR/SCC records before submitting to any Court of Law.</p>
               <h4 className="text-slate-900 font-bold">BNS Protocol Warning</h4>
               <p>The transition from IPC to BNS is ongoing. Mappings provided by the AI are indicative and should be cross-referenced with the latest Ministry of Home Affairs notifications.</p>
            </div>
          </div>
        );
    }
  };

  return (
    <div className="max-w-4xl mx-auto space-y-10 animate-in fade-in duration-700 pb-20">
      <header className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-6 pb-8 border-b border-slate-200">
        <div>
           <h2 className="text-4xl font-bold text-slate-900 legal-serif">Trust & Transparency</h2>
           <p className="text-slate-500 font-medium">Official governing documents for the Vidhi Enterprise Ecosystem.</p>
        </div>
        <div className="flex bg-white rounded-2xl border border-slate-100 p-1 shadow-sm">
           <button onClick={() => setTab('tos')} className={`px-4 py-2 rounded-xl text-[10px] font-bold uppercase tracking-widest transition-all ${tab === 'tos' ? 'bg-slate-900 text-white shadow-lg' : 'text-slate-400'}`}>TOS</button>
           <button onClick={() => setTab('privacy')} className={`px-4 py-2 rounded-xl text-[10px] font-bold uppercase tracking-widest transition-all ${tab === 'privacy' ? 'bg-slate-900 text-white shadow-lg' : 'text-slate-400'}`}>Privacy</button>
           <button onClick={() => setTab('disclaimer')} className={`px-4 py-2 rounded-xl text-[10px] font-bold uppercase tracking-widest transition-all ${tab === 'disclaimer' ? 'bg-slate-900 text-white shadow-lg' : 'text-slate-400'}`}>Disclaimer</button>
        </div>
      </header>

      <div className="bg-white p-12 rounded-[3.5rem] border border-slate-200 shadow-sm min-h-[500px]">
        {renderContent()}
      </div>

      <footer className="text-center py-10 opacity-30">
         <p className="text-[10px] font-bold uppercase tracking-[0.4em]">Vidhi OS • Secure • Compliant • Transparent</p>
      </footer>
    </div>
  );
};

export default Legal;
